version: "3.8"

services:
  app:
    build: .
    environment:
      PORT: 3000
      REDIS_HOST: redis
      REDIS_PORT: 6379
      DATABASE_URL: postgresql://heap:overflow@host.docker.internal:6500/heap_overflow
      JWT_SECRET: heap_overflow
      SESSION_SECRET: heap_overflow
    depends_on:
      - postgres
      - redis
    ports:
      - "3000:3000"

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: heap
      POSTGRES_PASSWORD: overflow
      POSTGRES_DB: heap_overflow
    ports:
      - "6500:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
